name: Secrets and variables demo

on:
  push

jobs:
  show-data:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: use secret
      run: 'echo "Using secret (masked): ${{ secrets.MY_SECRET_KEY }}"'

    - name: use variable
      run: 'echo "Environment varaible: ${{ vars.ENVIRONMENT }}"'
